
export const ActionTypes = {
  FETCH_PRODUCTS : "FETCH_PRODUCTS",
  SET_PRODUCTS : "SET_PRODUCTS",
  SELECTED_PRODUCTS :"SELECTED_PRODUCTS",
  REMOVE_SELECTED_PRODUCTS :"REMOVE_SELECTED_PRODUCTS",
  CART_PRODUCTS:"CART_PRODUCTS"
}
